1.21.30 support
PrismarineJS/bedrock-protocol pull request #527
Opened 2024-09-18 21:29 UTC by pokecosimo

2024-09-19 19:44 UTC, Kaaaaii approved these changes

2024-09-19 20:40 UTC, TSL534 requested changes
bro did not update the packets

2024-09-19 21:09 UTC, Kaaaaii commented
> bro did not update the packets

This pull request is connected to https://github.com/PrismarineJS/minecraft-data/pull/911

2024-09-19 22:00 UTC, Slauh commented
pluh

2024-09-20 07:50 UTC, merged

2024-09-20 07:50 UTC, extremeheat commented
/makerelease